version: "3"
services:
  consumer-service:
    container_name: consumer-service
    image: rodolpheche/wiremock
    networks:
      - consumer_network
      - mockrunner_bridge
    volumes:
      - ./consumer-service/src:/home/wiremock
      - ./consumer-service/extn:/var/wiremock/extensions
    ports:
      - 9000:8080
    command:
      - -global-response-templating
      - -verbose

  consumer-service-isolated:
    container_name: consumer-service-isolated
    image: rodolpheche/wiremock
    networks:
      - consumer_network
    volumes:
      - ./consumer-service/src:/home/wiremock
      - ./consumer-service/extn:/var/wiremock/extensions
    ports:
      - 9001:8080
    command:
      - -global-response-templating
      - -verbose

networks:
  consumer_network:
    name: consumer_network
  mockrunner_bridge:
    external: true
